- name: install apache2 and php packages for Debian
  tags: apache2,php
  apt:
    name:
      - "{{ apache_package_name  }}"
      - "{{ php_package_name }}"
    state: latest
  when: ansible_distribution == "Debian", "Ubuntu"

#- name: restart apache2
#  tags: apache2, restart
#  service:
#    name: apache2
#    state: restarted
#    enabled: yes
#  when: ansible_distribution == "Debian", "Ubuntu"

#- name: copy html file for site
#  tags: apache,apache,apache2,httpd
#  copy:
#    src: default_site.html
#    dest: /var/www/html/index.html
#    owner: root
#    group: root
#    mode: 0644

- name: change Ansible line
  tags: apache,debian
  lineinfile:
    path: /var/www/html/index.html
    regexp: 'Ansible'
    line: "        Ansible is AWESOME!!!!"
  when: ansible_distribution == "Debian"
#  register: linechanged
  notify: restart_apache

#- name: restart again apache2
#  tags: apache,debian
#  service:
#    name: "{{ apache_service }}"
#    state: restarted
#  when: linechanged.changed
