- name: Add Webmin repository
  tags: webmin 
  template:
    src: "{{ webmin_repo }}"
    dest: "{{ webmin_repo_folder }}"
    owner: root
    group: root
    mode: 0644

- name: Add Webmin key
  apt_key:
    url: "{{ webmin_gpg_key_url }}"
    state: present

- name: Install ncdu, gnupg2 and Webmin package
  apt:
    name: ncdu, gnupg2, webmin
    update_cache: yes